// Mã lỗi API dùng chung cho server và client. Response lỗi: { error: { code, message, details? } }.
export const ERROR_CODES = {
  VALIDATION_ERROR: 400,
  BAD_REQUEST: 400,
  CANNOT_MODIFY_SELF: 400,
  WRONG_PASSWORD: 400,
  INVALID_CATEGORY: 400,
  INVALID_IMAGE: 400,
  INVALID_UNIT: 400,
  INVALID_CONTACT: 400,
  INVALID_DISCOUNT: 400,
  AMOUNT_TOO_LARGE: 400,
  DEBT_REQUIRES_CUSTOMER: 400,
  DEBT_REQUIRES_SUPPLIER: 400,
  REASON_REQUIRED: 400,
  TOO_MANY_LINES: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN: 403,
  ACCOUNT_DISABLED: 403,
  CSRF_REJECTED: 403,
  PRICE_BELOW_COST: 403,
  NOT_FOUND: 404,
  PRODUCT_NOT_IN_COUNT: 404,
  PHONE_TAKEN: 409,
  LAST_OWNER: 409,
  CODE_TAKEN: 409,
  BARCODE_TAKEN: 409,
  CATEGORY_IN_USE: 409,
  CATEGORY_NAME_TAKEN: 409,
  NEGATIVE_STOCK: 409,
  OUT_OF_STOCK: 409,
  PRODUCT_INACTIVE: 409,
  DEBT_LIMIT_EXCEEDED: 409,
  ALREADY_CANCELLED: 409,
  INVALID_STATUS: 409,
  IDEMPOTENCY_CONFLICT: 409,
  CANNOT_CANCEL_STOCK_USED: 409,
  IMAGE_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  TOO_MANY_ATTEMPTS: 429,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export interface ApiErrorBody {
  error: { code: ErrorCode; message: string; details?: unknown };
}

/** Lỗi từng trường khi validate thất bại (details của VALIDATION_ERROR). */
export interface FieldError {
  path: string;
  message: string;
}
